### ISSUE TITLE
New Blogging website

### ISSUE THREAD

**Issue by cderv** [rbind/support#12]
Hi, 

I was thinking for some time now to start blogging with the help of blogdown. I just found out about netlify and now about rbind. It seems that everything tells me that I should start. 
I have a netlify account, but not yet a repo for my blog in my GH account. 
How should I proceed ?

**Comment by yihui** [comment]
I have sent you an invite to join rbind. Please read https://support.rbind.io/about/ to proceed.

**Comment by cderv** [comment]
Thanks. I have read the about page.
Will call the repository cderv as it will be my personnal bloging website. 

As I don't know really where to start, I will begin to study others blogdown site to see how to begin. 
If you have some advice, feel free!

**Comment by thercast** [comment]
@cderv we are happy to have you on board!  I recently went through the process of converting my site from a previous framework to `blogdown` and you can read more details about my experience [here](https://support.rbind.io/2017/04/27/r-podcast-website/).  Here's what I would recommend to proceed:

1. Accept the invitation that Yihui sent to join rbind so we can create a repository for you.  It sounds like you want it called cderv so it would be located at `github.com/rbind/cderv`.  
2. Visit the online version of the  [`blogdown`](https://bookdown.org/yihui/blogdown/) book that's currently in development and follow the instructions in the [get started](https://bookdown.org/yihui/blogdown/get-started.html) section to get your environment set up.  I would keep things simple and use the default theme to start, but as you get more comfortable with `blogdown` and by extension `Hugo` you can pick one of the [many themes](http://themes.gohugo.io/) available if you want to change.
3. This is mentioned in the aforementioned book but I'd highly recommend using RStudio to develop your `blogdown` site so you can take advantage of the great add-ins to preview your site and create new posts.  I used the live preview extensively so I could view my changes in real time during my many tweaks.
4. Once you have a working version of  your site ready to go, push the files to the aforementioned GitHub repository.  I recommend putting your `public` subdirectory in the `.gitignore` file since netlify will actually compile the site for you in a fresh instance and does not need the `public` directory.  Plus it will make your repository cleaner.  You can see my [`.gitignore`](https://github.com/rbind/r-podcast/blob/master/.gitignore) file if that helps.
4. Visit [netlify.com](https://www.netlify.com/) and create an account by linking it to your GitHub account.  Yihui has good documentation on the process in the [deployment section](https://bookdown.org/yihui/blogdown/netlify.html) of the `blogdown` book.  I specified `hugo_0.19` in the build configuration so it matched my local version of `hugo`.  Otherwise the process is very straight-forward.  Then you can see what your site looks like with the custom URL that netlify provides.  I already had a custom domain of `r-podcast.org` that I specified in the netlify deployment settings, but we are also offering a domain `*.rbind.io` with whatever name you want your site to have.  

Let me know if you have any questions about the procedure and I'll be glad to assist.

**Comment by cderv** [comment]
Thanks! Nice welcoming and introduction ! 
I will do all this step by step and come back here if needed or when done.

**Comment by thercast** [comment]
@cderv I have a repository set for you on rbind at <https://github.com/rbind/cderv> and you should have full permissions to push your local files of the site to the repository when you're ready.  I want you to have a smooth experience getting your site off the ground, so if you'd like me to get you set up with a simple site as a starting point let me know and I'd be happy to do that for you.

**Comment by cderv** [comment]
Just to let you know as I did not answer you right away that I am working on my blog following your advices. Netlify is set up, no difficulties there, and I am trying now some themes. Not all themes are obvious and fully working. I will still try and keep you updated.

**Comment by cderv** [comment]
Hello, 
is it possible to have `cderv.rbind.io` domain ? 
I deployed my blog on netlify. my subdomain is choreographer-dog-82283

thanks

**Comment by yihui** [comment]
Of course! I just set the subdomain for you, and you need to configure it on your side, too: https://support.rbind.io/about/

**Comment by cderv** [comment]
Thanks ! All set up & working.

**Comment by thercast** [comment]
Glad you have everything working!  I'll close the issue for now but feel free to contact us if you have any other issues to discuss.

**Comment by yihui** [comment]
After you have more content on your website, please feel free to write a post introducing your website on https://support.rbind.io
