### ISSUE TITLE
New Subdomain Request

### ISSUE THREAD

**Issue by mayank634** [rbind/support#124]
Hi,

I would like to request a new rbind.io subdomain for my exisiting netlify subdomain. The details are mentioned below

### Netlify website address

pensive-mcnulty-2023ca.netlify.com/

### Preferred rbind.io subdomain

mydatavoyage.rbind.io

**Comment by road2stat** [comment]
@mayank634 - I have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

Thanks!

**Comment by mayank634** [comment]
Thank you so much!

**Comment by mayank634** [comment]
@road2stat When I try to access the website using  https://mydatavoyage.rbind.io/ I get a security error like this

![webpage](https://user-images.githubusercontent.com/6551645/35232834-85a4ba7e-ffc2-11e7-9ce4-3de543a6be8a.png)

And when I try to using http://mydatavoyage.rbind.io/ I get the below page without any styling

![webpage](https://user-images.githubusercontent.com/6551645/35232651-0ddcceaa-ffc2-11e7-8bfd-bddd4ce01c52.png)

Can you please look into this? 

Thanks in advance

**Comment by road2stat** [comment]
Hi @mayank634 - good question -- if you need SSL (https) for the rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS). It's just one click away.

The reason why the styles disappeared: when you load the website with `http` protocol, the js and css assets were forced to be loaded with `https` protocol instead of `http` (this depends on how the urls were set in the template, relative or absolute, protocol-relative or not). Since the `https` urls for these assets are not accessible (certificate problem as above), they will not be properly loaded and rendered.

All issues should be solved right after the rbind.io subdomain TLS certificate is enabled on Netlify.
