### ISSUE TITLE
my rbind.io is not updating

### ISSUE THREAD

**Issue by drkamarul** [rbind/support#125]
Hi,
Mine is <https://github.com/rbind/drkamarul>. I pushed a new post and an edited an older post to rbind. The last push was today. But the webpage does not update. Did I miss anything ie I am not the admin of the my rbind.io. I also note that there is only 1 contributor that is @thercast . rbind folks and @thercast , can you help me? Best wishes.

**Comment by thercast** [comment]
Hi @drkamarul, there seems to be an issue with the DNS record for your site.  I'm not sure how it happened but the CNAME record for your site alias of http://drkamarul.rbind.io/ is pointing to a different domain for your site at http://hydrographer-radio-54151.netlify.com/ (you'll see if you visit this site that it has your updated content) and not https://drkamarul.netlify.com/, which is current specified in the Netlify deployment settings.  I'll try to get the deployment routed to the correct site.

**Comment by thercast** [comment]
@yihui sorry to trouble you for this, but I tried to change the CNAME record for @drkamarul's site in your rbind DNS app so that it points to https://drkamarul.netlify.com/ instead of https://hydrographer-radio-54151.netlify.com  (which the current CNAME record points to) but the app gave an error (I'm guessing the app doesn't allow modifying existing records).  Do you have any suggestions on how we can fix this?

**Comment by yihui** [comment]
@thercast I have changed the CNAME record and pointed to drkamarul.netlify.com (you aren't able to do this from the app I gave you).

**Comment by drkamarul** [comment]
Hi @thercast , @yihui, please let me know if there are things I need to do on my part. My apology for taking your time during this festive season.

**Comment by drkamarul** [comment]
Hi @thercast , @yihui
