### ISSUE TITLE
Requesting rbind.io subdomain

### ISSUE THREAD

**Issue by joongsup** [rbind/support#145]
Requesting rbind.io subdomain, using the provided template. 

Thanks for your time.

### Netlify website address

uncmbbtrivia.netlify.com

### Preferred rbind.io subdomain

joongsup.rbind.io

**Comment by road2stat** [comment]
@joongsup - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by joongsup** [comment]
Thanks @road2stat for a quick response! Really appreciate what you guys are doing for the community. Would like to join the volunteering group as well in near future!

**Comment by yihui** [comment]
@joongsup I think we always need volunteers to help future users!

@road2stat Do you think you can easily handle the current amount of requests?

**Comment by joongsup** [comment]
@yihui @road2stat I'm not that familiar with domain management at the moment, but I'm willing to help in any way I can :) Also, sorry for commenting on a closed issue, but is there a way to redirect the visit to netlify address to the new rbind.io one? Thanks again for your time!

**Comment by yihui** [comment]
See the last section: https://yihui.name/en/2017/11/301-redirect/

**Comment by joongsup** [comment]
@yihui Amazing! Realizing should've googled better, but thanks again for your time. Please let me know if I can be of any help!

**Comment by road2stat** [comment]
@yihui - the current amount is ok -- around 1 request per day by eyeball estimation. That said, we could surely use some more helping hands to prepare for the future.

**Comment by yihui** [comment]
Okay. @joongsup If you are willing to help, there is one thing I was hoping someone could do: invite more people to join the rbind organization on Github, and suggest them transfer their website repositories to rbind (this is optional). You can find those people in the many old issues of this repo. If you want to volunteer, I'll convert you to an admin of this organization.

**Comment by joongsup** [comment]
Sure thing @yihui I’ll see what I can do!

**Comment by yihui** [comment]
@joongsup I have invited you to join as an admin. Please be extra cautious since you will have the full admin privileges (e.g., you will be able to kick me out if you want :).

Basically I want you to invite users to rbind https://github.com/orgs/rbind/people and ask if they are willing to transfer their existing website repo to rbind:

https://github.com/rbind/support/blob/master/content/about.md

I hope that most R and stats-related websites can be hosted in a single organization, so that it will be easier for users to learn from each other's websites. Once they transfer, you need to make them the admin of their own repo from the repo settings (N.B. not the admin of rbind, but the admin of a specific repo).

You can do these things at any time you like. Personally I don't really care much about whether people join rbind or not.

**Comment by yihui** [comment]
Oh actually another thing I wish someone can help: #38. I hope someone can remind existing rbind members to update the description and actual website URL of their repos. In particular, some people's repositories don't have the URLs.

![image](https://user-images.githubusercontent.com/163582/35695684-e272b726-074a-11e8-827a-75d0667651de.png)

**Comment by joongsup** [comment]
@yihui First step was to transfer my repo to rbind and it's done! As I thought it'd be automatically done somehow when my rbind.io subdomain was created (thanks to @road2stat), maybe we can start from there? I.e., Remind new ticket users that once rbind.io subdomain is created (through rbind/support), users have an option of transferring their repo to rbind. I'll keep thinking about what else can be done (maybe a blog post about this : ))

**Comment by yihui** [comment]
Sounds good!

**Comment by joongsup** [comment]
@yihui I wrote a draft blog [post](https://github.com/rbind/uncmbbtrivia/blob/master/content/post/2018-02-06-rss-feed.Rmd) that talks about moving site source repo to under rbind repo as I tried to turn on RSS feed. Doesn't XMin theme come with /layouts/rss.xml file?

**Comment by yihui** [comment]
@joongsup XMin does not have an RSS template, but it is easy to add one. You can start from Hugo's default template: https://gohugo.io/templates/rss/ I think the most desired change to most users would be to show the full content, i.e. change

```
<description>{{ .Summary | html }}</description>
```

to

```
<description>{{ .Content }}</description>
```

You may want to limit the number of entries via `rssLimit` in config.toml ([example](https://github.com/rbind/yihui/blob/master/config.yaml#L11)), otherwise you may end up with a huge RSS feed when you have a large number of posts (like me).

**Comment by joongsup** [comment]
@yihui Yeah indeed the blog [post](https://joongsup.rbind.io/post/2018/02/06/rss-feed/) (which is now published) talks about how I figured out RSS set up by using rbind github repo and seeing what ppl have in their repo.
