### ISSUE TITLE
Apply for a new rbind domain

### ISSUE THREAD

**Issue by guhjy** [rbind/support#166]
Please use this template for new rbind.io subdomain requests. Thank you!

### Netlify website address
https://loving-hamilton-f3ca0d.netlify.com

### Preferred rbind.io subdomain

guhjy.rbind.io

**Comment by road2stat** [comment]
@guhjy - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by road2stat** [comment]
Hi @guhjy , I just want to follow up since it seems the rbind subdomain still haven't been added to the Netlify website (showing "not found"). Is there anything we could help? Please let us know. -Nan

**Comment by chunyufen** [comment]
Hi, good afternoon. Thanks for the rbind.io account. I have problems. Let me explain.
1) I went to the Netlify account. I went to Domain management. I added the rbind.io account.
2) I amend my config.toml (changing the base URL to my new rbind.io account).
3) I sent to (push; I am sorry, I seldom use technical terms) my github.
4) Two problems occurred. They are:
a) my local site became ugly.
b) the website became ugly too.
Let me attach the screen print to you.
![screen shot 2018-05-19 at 2 25 07 pm](https://user-images.githubusercontent.com/18733971/40265764-46ed99bc-5b71-11e8-8316-214b3fc9dbd7.png)
The above screen shot showed you what I had done at netlify.
![screen shot 2018-05-19 at 2 32 15 pm](https://user-images.githubusercontent.com/18733971/40265779-79d618d6-5b71-11e8-8c78-e4ede69a0f3c.png)
The second screen shot above showed you my local site. It was not like this.
![screen shot 2018-05-19 at 2 33 14 pm](https://user-images.githubusercontent.com/18733971/40265792-a1e7919c-5b71-11e8-98ed-200507dace6a.png)
The third screen shot above showed you the rbind.io web. It was same as local -- ugly.
What was the original view? I show you next image.
![screen shot 2018-05-19 at 2 34 41 pm](https://user-images.githubusercontent.com/18733971/40265804-df7ef216-5b71-11e8-9aa7-b7145311b0fe.png)
So, I must have done something wrong.
Please help me.
Thank you very much.

**Comment by road2stat** [comment]
@guhjy - just wanna check in quickly, - any issues in setting up the website and adding the custom domain?

**Comment by road2stat** [comment]
Hi @guhjy - I just want to do another follow up as we are doing some housekeeping for the rbind support tickets which are open for a long time.

Any chance you could kindly add the subdomain to the Netlify website? It probably only takes about two minutes to do so. It would be very helpful though because we will be able to close this ticket.

If that's not possible, to avoid clutter in the opened tickets, I'm proposing we remove the requested subdomain on our side so that we can close the ticket (this will happen in about a week). If it happens, please always feel free to open a new issue to submit another request in the future, and we will be always happy to help.

Thanks!
-Nan

**Comment by road2stat** [comment]
Dear @guhjy,

Since we haven't heard back from you on adding the subdomain to an active website for a considerably long time, we have removed the subdomain (`guhjy.rbind.io`) you requested in this issue. This housekeeping action helps us improve our support quality, reduce security risks, and ensure that the resource is shared equitably by all the community members (#276).

In the future, please feel free to create a new issue to submit subdomain requests when your website is ready. Again, thank you for your support, and we are looking forward to working with you soon.
