### ISSUE TITLE
rbind.io request

### ISSUE THREAD

**Issue by entr0py43** [rbind/support#170]
Thanks for this!  Awesome community support!

###hugo theme
beautifulhugo
https://github.com/halogenica/beautifulhugo

### Netlify website address
entropy.netlify.com

### Preferred rbind.io subdomain
entropy.rbind.io

**Comment by road2stat** [comment]
@entr0py43 - welcome to rbind! We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need SSL (https) for the rbind.io subdomain, please also enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!

**Comment by road2stat** [comment]
Hi @entr0py43, I just want to follow up since it seems the Netlify website doesn't exist and the rbind subdomain hasn't been added to it (showing "not found"). Is there anything we could help? Please let us know. -Nan

**Comment by entr0py43** [comment]
Hey, i changed the name i thought, i got sidetracked.. i'll keep you posted in the next couple weeks if i need help. thanks for reaching out!!    

    On Thursday, March 15, 2018, 7:42:16 PM EDT, Nan Xiao <notifications@github.com> wrote:  
 
 
Hi @entr0py43, I just want to follow up since it seems the Netlify website doesn't exist and the rbind subdomain hasn't been added to it (showing "not found"). Is there anything we could help? Please let us know. -Nan

**Comment by road2stat** [comment]
@entr0py43 - just wanna check in quickly, - any issues in setting up the website and adding the custom domain?

**Comment by entr0py43** [comment]
Haven't had the time Nan.. hoping to in the near future.  Appreciate the effort, will try to put some time into this in the next couple months.
    On Friday, July 6, 2018, 3:32:56 PM EDT, Nan Xiao <notifications@github.com> wrote:  
 
 
@entr0py43 - just wanna check in quickly, - any issues in setting up the website and adding the custom domain?

**Comment by road2stat** [comment]
Hi @entr0py43 - I just want to do another follow up as we are doing some housekeeping for the rbind support tickets which are open for a long time.

Any chance you could kindly add the subdomain to the Netlify website? It probably only takes about two minutes to do so. It would be very helpful though because we will be able to close this ticket.

If that's not possible, to avoid clutter in the opened tickets, I'm proposing we remove the requested subdomain on our side so that we can close the ticket (this will happen in about a week). If it happens, please always feel free to open a new issue to submit another request in the future, and we will be always happy to help.

Thanks!
-Nan

**Comment by road2stat** [comment]
Dear @entr0py43,

Since we haven't heard back from you on adding the subdomain to an active website for a considerably long time, we have removed the subdomain (`entropy.rbind.io`) you requested in this issue. This housekeeping action helps us improve our support quality, reduce security risks, and ensure that the resource is shared equitably by all the community members (#276).

In the future, please feel free to create a new issue to submit subdomain requests when your website is ready. Again, thank you for your support, and we are looking forward to working with you soon.
