### ISSUE TITLE
Website Request!

### ISSUE THREAD

**Issue by hnhd** [rbind/support#224]
Hi there. So happy to join this community. I wanted to create a website that used the Hugo Future Imperfect format. Would that be doable? 

### Netlify website address

Not gonna use netlify—I've got my own personal domain.

### Preferred rbind.io subdomain

hnhd.rbind.io

**Comment by road2stat** [comment]
@hnhd I think this is conceptually doable. I've added the subdomain you requested and pointed it to your domain (hhaddad.com). It now looks like to be pointed to the corresponding rbind repo served using GitHub Pages.

So, would you mind transferring your website repo (https://github.com/hnhd/hhaddad-website) to the rbind organization? I've sent you the invitation. Please name the transferred repo as `hnhd.rbind.io`. (although the rbind subdomain will probably still be redirected to the top level domain.)

**Comment by hnhd** [comment]
Oh, I'll be keeping that repository for myself in the meantime—I'll just make a separate one to transfer.

(sorry for the delay in response)

**Comment by hnhd** [comment]
Just transferred the repository and made it accessible to the admins. Does that work?

**Comment by yihui** [comment]
@hnhd I'm a little confused: do you just want us to point hnhd.rbind.io to hhaddad.com? If that is the case, it is already done, and I think you just need to add a record in your CNAME: https://github.com/hnhd/hhaddad-website/blob/gh-pages/CNAME

**Comment by hnhd** [comment]
Hi @yihui—thanks for helping. I just wanted to leave the website on hnhd.rbind.io while I play with it and then transfer it over to hhaddad.com when it's ready.

**Comment by road2stat** [comment]
Hi @hnhd - I just want to do another follow up as we are doing some housekeeping for the rbind support tickets which are open for a long time.

Any chance you could kindly add the rbind subdomain to the CNAME file (as Yihui suggested above)? It would be very helpful because we will be able to close this ticket.

Thanks a lot!
-Nan

**Comment by road2stat** [comment]
Dear @hnhd,

Since we haven't heard back from you on adding the subdomain to an active website for a considerably long time, we have removed the subdomain (`hnhd.rbind.io`) you requested in this issue. This housekeeping action helps us improve our support quality, reduce security risks, and ensure that the resource is shared equitably by all the community members (#276).

In the future, please feel free to create a new issue to submit subdomain requests when your website is ready. Again, thank you for your support, and we are looking forward to working with you soon.
