### ISSUE TITLE
Request for a rbind.io sub domain

### ISSUE THREAD

**Issue by seewe** [rbind/support#243]
Netlify website address

ewanesergio.netlify.com

Preferred rbind.io subdomain

ewanesergio.rbind.io

Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

Thank you !

**Comment by road2stat** [comment]
@seewe - we have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS).

Thanks!
-Nan

**Comment by seewe** [comment]
thank you !!!

**Comment by road2stat** [comment]
@seewe - just a regular follow-up -- I'm still seeing 404 on the Netlify address. Any help needed when creating the website?  -Nan

**Comment by road2stat** [comment]
@seewe - just wanna checking in case the previous one was buried among notifications -- is any issues on creating the website? Please just let us know if you got any questions. -Nan

**Comment by road2stat** [comment]
Hi @seewe - I just want to do another follow up as we are doing some housekeeping for the rbind support tickets which are open for a long time.

Any chance you could kindly add the subdomain to the Netlify website? It probably only takes about two minutes to do so. It would be very helpful though because we will be able to close this ticket.

**Comment by road2stat** [comment]
Dear @seewe,

Since we haven't heard back from you on adding the subdomain to an active website for a considerably long time, we have removed the subdomain (`ewanesergio.rbind.io`) you requested in this issue. This housekeeping action helps us improve our support quality, reduce security risks, and ensure that the resource is shared equitably by all the community members (#276).

In the future, please feel free to create a new issue to submit subdomain requests when your website is ready. Again, thank you for your support, and we are looking forward to working with you soon.
