### ISSUE TITLE
Request for rbind.io subdomain

### ISSUE THREAD

**Issue by moo99** [rbind/support#250]
## Netlify website address

festive-kirch-c42314.netlify.com

## Preferred rbind.io subdomain

moo99.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by isteves** [comment]
@moo99 We have configured the rbind subdomain you requested. Please [set the rbind subdomain](https://support.rbind.io/about/) in your Netlify account.

![](https://user-images.githubusercontent.com/163582/31508235-11282aa2-af43-11e7-8204-3d019ef7fe33.png)

If you need HTTPS for your rbind.io subdomain, please enable the automatic TLS certificates for it on Netlify (Domain management -> HTTPS). 

Thanks!
Irene

**Comment by road2stat** [comment]
@moo99 - just a follow-up, any issues in configuring the subdomain?

**Comment by yihui** [comment]
In particular, I wonder if HTTPS for *.rbind.io works or not, because we recently worked with Netlify to use a wildcard SSL certificate.

**Comment by road2stat** [comment]
@moo99 - just wanna do a regular follow up again --  were there any issues when adding the rbind subdomain? Please just let us know if there is any. It only takes one minute to do it -- when it's done we can close this ticket.

**Comment by road2stat** [comment]
Hi @moo99 - I just want to do another follow up as we are doing some housekeeping for the rbind support tickets which are open for a long time.

Any chance you could kindly add the subdomain to the Netlify website? It probably only takes about two minutes to do so. It would be very helpful though because we will be able to close this ticket.

**Comment by road2stat** [comment]
Dear @moo99,

Since we haven't heard back from you on adding the subdomain to an active website for a considerably long time, we have removed the subdomain (`moo99.rbind.io`) you requested in this issue. This housekeeping action helps us improve our support quality, reduce security risks, and ensure that the resource is shared equitably by all the community members (#276).

In the future, please feel free to create a new issue to submit subdomain requests when your website is ready. Again, thank you for your support, and we are looking forward to working with you soon.
