### ISSUE TITLE
create a new site

### ISSUE THREAD

**Issue by kang-yu** [rbind/support#30]
Hi Yihui,

I would like to create a blogdown site for me with the subdomain `kangyu.rbind.io`. Actually, I have a GitHub repo kang-yu.github.io that was generated with pelican, but the source files were lost due to lost of my laptop two years ago... I don't know whether it is possible or not to transfer it here. 

Cheers,
Kang

**Comment by yihui** [comment]
I looked at your website and you do not really have a huge amount of pages, so I suggest you just copy and paste the pages to Markdown files and tweak them a bit when necessary.

I have invited you to join rbind, and you should be able to create the repo by yourself, but let us know anyway if you really need help after you read at least the Chapter 1 of the [blogdown book](https://bookdown.org/yihui/blogdown/). Our human resources are limited at the moment, and we can definitely help if you have no GIT/Github experience.

Since you have your own domain name, I don't think you really need the rbind.io subdomain unless you think it is cool :) You can connect your repo with Netlify and use your own custom domain for free (more info in the blogdown book and Netlify docs).

**Comment by kang-yu** [comment]
Thanks for the invitation, Yihui! I was wondering I have to claim a subdomain name like a github username, and of course it is cool:) I am trying Netlify.

**Comment by yihui** [comment]
I have set the CNAME record of `kangyu.rbind.io` to `kangyu.netlify.com`. Please feel free to use it on Netlify. 

![](https://cloud.githubusercontent.com/assets/163582/26532991/e3e5bb40-4453-11e7-9bbb-ad54f5e14d09.png)
