### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by CarlvinJerry** [rbind/support#343]
Hello, thanks @road2stat for setting up the subdomain for me, really appreciate. One last question, how do I get SSL (HTTPS) certificate for the same? Here is the website 

Http://beyondrawdata.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by road2stat** [comment]
@CarlvinJerry -HTTPS already works (try https://beyondrawdata.rbind.io/). You can set the Hugo `baseURL` to `https://beyondrawdata.rbind.io/` so that the CSS/JS files are loaded correctly (now they are redirected to the HTTP version and don't get loaded under HTTPS due to mixed content).

If you use Netlify in the future, you may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.
