### ISSUE TITLE
HTTPS request blocked

### ISSUE THREAD

**Issue by CarlvinJerry** [rbind/support#344]
@road2stat changing my base URL to https://beyondrawdata.rbind.io gives me a mixed content error. However if I build with http... it seems to be working just fine, could this have to do with cache?

**Comment by CarlvinJerry** [comment]
![image](https://user-images.githubusercontent.com/38648589/51862072-d6392000-234e-11e9-9948-b2909a139ddd.png)
Here's what I'm getting. While the http;//beyondrawdata.rbind.io seems to be showing posts I already deleted/modified

**Comment by road2stat** [comment]
@CarlvinJerry -it doesn't look like cache. After changing the baseurl, the re-generated site should have all the base urls changed to the https version of the rbind subdomain. This means, for example, if you view the HTML source for each page, the CSS links should start with ` https://beyondrawdata.rbind.io/css/...` instead of `https://CarlvinJerry.github.io/css/...` -- it seems to me they are still using the github.io links. Please check if the site is really regenerated, with the correct baseurl in the HTML source, and pushed to the correct GitHub repo.

**Comment by CarlvinJerry** [comment]
Thank you so much for pointing that out @road2stat , it actually worked! All I needed to do was pull then push to the repo again. Thanks!

**Comment by road2stat** [comment]
-that's great! Glad it works! 👍
