### ISSUE TITLE
Domain Name Request - RLadies Latam blog

### ISSUE THREAD

**Issue by brunaw** [rbind/support#357]
Hello :) can we have a `.rbind.io` domain for the R-Ladies LatAm blog (https://github.com/rladies/blog-rladies-latam)?

**Comment by road2stat** [comment]
@brunaw -of course! We are more than happy to offer the rbind subdomain and support here. Please just let us know the rbind.io subdomain you prefer, and where to point it to (for example, the address for the deployed website on Netlify). Please feel free to create another issue with the issue template, or simply reply here.

**Comment by brunaw** [comment]
Hi @road2stat, thanks :) The domain can be rladieslatam.rbind.io, and the github repository of the website is: https://github.com/rladies/blog-rladies-latam (is this what you asked? let me know if I need to do something else)

**Comment by road2stat** [comment]
@brunaw -almost. One thing you still need to do is getting the website in the repo deployed somewhere first. Check this chapter in the blogdown book for options and recommendations: https://bookdown.org/yihui/blogdown/deployment.html. After it's deployed, please let us know the website address so that we can point `rladieslatam.rbind.io` to it.

**Comment by road2stat** [comment]
hey @brunaw -just want to follow-up on this, any help needed for getting the site deployed? I've seen a `docs` folder containing the generated site but not really sure about the deployed site's address. As soon as you decided where to host the site and get it deployed there, we'll know how to proceed.

**Comment by brunaw** [comment]
Hi @road2stat, thanks for the concern :) hmmmm kind of, I'm trying to deploy from master branch in Netlify, but it's not working out and I'm not sure why (the deploy has no errors, but the final URL is broken)  :-( and I believe I can't use github pages since I already have a blog with my username

**Comment by road2stat** [comment]
@brunaw -ok, sounds very close! We probably just need to be a bit more specific to figure out what "the final URL is broken" means -- do you have the deployed site's address on Netlify (`something.netlify.com`) so we can take a look?

**Comment by brunaw** [comment]
yes @road2stat, the URL is https://rladieslatam.netlify.com/ :) it just says that the page was not found

**Comment by road2stat** [comment]
@brunaw -ok, looks like it's a site created by radix instead of blogdown. So we just need to follow the [guide for deploying radix sites to Netlify](https://rstudio.github.io/radix/publish_website.html#netlify), see also the [previous discussion](https://github.com/rstudio/radix/issues/74) on this.

You probably need to tweak the "Publish directory" settings under "Settings" -> "Build & deploy" -> "Building settings" to where the actual `output_dir` is, meaning `docs` in your case, and remove the "Build command" if any. If you need to check the deployment logs on Netlify, click "Deploys" -> click "Production: master@HEAD", then you will be able to see the build log and preview "the build".

There are some [differences between radix and blogdown](https://emitanaka.rbind.io/post/scientific-and-technical-blogging-radix-vs-blogdown-remix/), but the main difference on the deployment part for radix is that Netlify will not able to build your site on their servers for you (unlike Hugo, the rmarkdown toolchain is not available). Instead, it reads and deploys content from the locally built `output_dir` directly. This means you need to remember to render the site locally when changing the site's content, and push the changes for both source and the rendered site to GitHub. Since you already used GitHub Pages (without Jekyll), this flow would be very similar to that.

**Comment by brunaw** [comment]
Thanks @road2stat, it was exactly it :) working now on https://rladieslatam.netlify.com/
I knew it was something to do with radix, but forget to check its manual :p

**Comment by road2stat** [comment]
@brunaw -that's great! Glad to see the site's working now. We have just configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by brunaw** [comment]
Done, thank you so much! 🎉

**Comment by road2stat** [comment]
-awesome, you're very welcome! 👍
