### ISSUE TITLE
Unable to access domain

### ISSUE THREAD

**Issue by UTexas80** [rbind/support#382]
I just updated my glen.c.falk.rbind.io site. The site is not rendering correctly and I am getting a "Can' connect securely to this page" error message. I contacted Netlify support and they suggested I modifiy my url from glen.c.falk.rbind.io to glencfalk.rbind.io.

Am I able to do this or is this something that is done on your side?

Thank you,
Glen

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@UTexas80 -sure thing, we can make the change. I can't promise it would fix the problem, but let's try. Please remember to update the Hugo config so that the CSS/JS files are pointed to the new subdomain.

@yihui -could you please help change `glen.c.falk.rbind.io` to `glencfalk.rbind.io`? I believe the previous one worked before, but not entirely sure what happened after that...

**Comment by yihui** [comment]
Done.

**Comment by nanxstats** [comment]
@UTexas80 -could you please remove the old custom domain on Netlify, and use the new subdomain `glencfalk.rbind.io` to see if it works?

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

**Comment by UTexas80** [comment]
Thank you Nan & Yihui for the prompt response. Much appreciated. Looks like the problem is sitting behind my keyboard. I updated my theme so I will have to re-check the code but I needed to change the url nonetheless.
Have a good day.
Glen

**Comment by nanxstats** [comment]
-great, looks like it's working! Closing now.
