### ISSUE TITLE
Invalid SSL certificate? 

### ISSUE THREAD

**Issue by MayaGans** [rbind/support#461]
I've been using the subdomain `maya.rbind.io` for my website (`mayagans.netlify.com` -- used to be `bayesianbabe.netlify.com`) for months, and just started seeing the error 

> The SSL certificate presented by the server did not pass validation. This could indicate an expired SSL certificate or a certificate that does not include the requested domain name. Please contact your hosting provider to ensure that an up-to-date and valid SSL certificate issued by a Certificate Authority is configured for this domain name on the origin server. Additional troubleshooting information here.

Any ideas? Thanks!

**Comment by nanxstats** [comment]
In our record, `maya.rbind.io` still points to `bayesianbabe.netlify.com` which now gives a 404  (see also https://github.com/rbind/support/issues/423). This might be the reason.

@yihui -could you please update the record to point it to `mayagans.netlify.com`?

**Comment by huttoncp** [comment]
I am having the exact same problem with my subdomain craig.rbind.io. However, since this seems to require updating the record anyways, can you please have it point to my new base URL craighutton.netlify.com?

**Comment by yihui** [comment]
@nanxstats Updated.

**Comment by yihui** [comment]
@huttoncp The Netlify subdomain doesn't really matter. It is not the URL that you'd actually advertise. What you tell people should be the rbind.io subdomain. You really don't need to change the Netlify subdomain. I strongly recommend that you redirect the Netlify subdomain to your "official" domain: https://yihui.name/en/2017/11/301-redirect/#another-application-redirect-netlify-com-to-your-own-domain

Changing the Netlify subdomain after it has been connected with an rbind.io subdomain can create some hassles (such as invalid SSL certificates). That said, I have updated the rbind.io DNS record for you anyway since you have already changed it on your side.

**Comment by huttoncp** [comment]
Thank you @yihui. The SSL certificate issue happened before I switched it (I noticed when I tried to access the craig.rbind.io domain for my site earlier this evening to work on my blog). I have the official rbind.io domain set as my primary one in my netlify account and it had been working fine since it was setup in May, so I'm not sure what went wrong. Not sure if this helps, but the error number was 526: Invalid SSL certificate. Sorry for the inconvenience and I greatly appreciate your time and assistance.

**Comment by yihui** [comment]
I don't know why, either. Perhaps try to delete the domain record on Netlify, and add it again? Sometimes the SSL certificate issue needs more time since changes in DNS records are often not propagated immediately.

**Comment by huttoncp** [comment]
Alright, I tried removing and re-adding it. There was a note that it can take 24 hours to update the netlify DNS record, so if you want we can close this issue for now and I can open a new one tomorrow night if it still isn't working.

**Comment by MayaGans** [comment]
Looks like it's working now, thank you!

**Comment by MayaGans** [comment]
Working now ??? Haha happy to close but kind of mysterious !
