### ISSUE TITLE
new rbind.io subdomain

### ISSUE THREAD

**Issue by GabrielKaiserQFin** [rbind/support#553]
## Netlify website address

https://pensive-pasteur-a90289.netlify.com/

## Preferred rbind.io subdomain

aiap.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.
I promise, many thanks!!!

**Comment by nanxstats** [comment]
@GabrielKaiserQFin -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by GabrielKaiserQFin** [comment]
Hi,

could you please add a CNAME record for aiap pointing to aiap.netlify.com.
aiap CNAME aiap.netlify.com.

It seems this was not done since Netlify states errors with the DNS
configuration:
"We could not provision a Let’s Encrypt certificate for your custom domain."

and https is not enabled.


Many thanks for your support and time,

Best
Gabbriel

Am Do., 6. Feb. 2020 um 22:38 Uhr schrieb Nan Xiao <notifications@github.com

**Comment by nanxstats** [comment]
@yihui -could you please update the record for `aiap.rbind.io` to `aiap.netlify.com`? Thanks!

@GabrielKaiserQFin -the https version for your rbind subdomain already works (handled by the rbind side instead of the Netlify side, and the error can be safely ignored). The http urls are not automatically redirected to the https urls though. You may find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting http traffic to https using a 301 redirect.

**Comment by GabrielKaiserQFin** [comment]
Many thanks, I succeeded in the end.

Am Fr., 14. Feb. 2020 um 14:30 Uhr schrieb Nan Xiao <
notifications@github.com>:

**Comment by yihui** [comment]
Sure. Updated.
