### ISSUE TITLE
Subdomain request for ouzhang

### ISSUE THREAD

**Issue by zhangou888** [rbind/support#556]
## Netlify website address

ouzhang.netlify.com

## Preferred rbind.io subdomain

ouzhang.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@zhangou888 -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by chunyufen** [comment]
# Netlify address:

"https://yufen-chun.netlify.com/"

# Preferred rbind.io subdomain
"https://yufen-chun.rbind.io"

# History

I put my website in GitHub since 2017. A few days ago, GitHub could not build the website. I suspected it is because of update of Hugo, either Hugo theme has not been updated or GitHub has not been updated.

I changed to BitBucket. I wish to keep my previous rbind.io subdomain: "https://yufen-chun.rbind.io"

Please help.

**Comment by nanxstats** [comment]
Hey @chunyufen -since I'm closing this issue, could you please do us a favor and create a new issue and describe the problem in there? Thanks.
