### ISSUE TITLE
New rbind.io subdomain request for my new website

### ISSUE THREAD

**Issue by statimatics** [rbind/support#56]
Hello,
I've been following blogdown for quite sometime now but I couldn't actually get it to work earlier because of the limited resources. I recently checked the documentation again and was amazed at the amount of work you've put into the documentation. Your work paid off and I am now able to set up my website. I went with the hugo lithium theme but with the fonts of your (yihui.name) website as I like it a lot.
I would like to request the subdomain statimatics.rbind.io. My website (it's still in progress) is currently on netlify with the name statimatics.netlify.com.
Furthermore, I would appreciate if you can guide me on how to direct my domain name (statimatics.com) to this website also if that's not a problem.
I appreciate your work.
Oluwasegun

**Comment by yihui** [comment]
Done. If you have problems with adding statimatics.rbind.io to your site on Netlify, please see #42.

For your domain, please see https://bookdown.org/yihui/blogdown/dns-records.html You can bind multiple domains to your site on Netlify, but I guess it is probably not necessary. Since you have your own apex domain, I recommend you just use that instead of an rbind.io subdomain, unless you think the latter looks cool :)

As for the blogdown documentation, it was far more challenging to write than I imagined. There were times when I wanted to kill myself due to the sheer amount of technologies that I had to explain. Anyway, building a website has been much easier anyway thanks to R Markdown, Hugo, and Netlify.

**Comment by statimatics** [comment]
Thanks a lot. Just like you anticipated, I encountered the same error in #42. I've sent the netlify support a mail to help out.
As regards the domain, I sure find the .rbind.io subdomain very cool and I see rbind exploding with lots of users very soon. It will be such a shame to miss out on my own custom rbind.io subdomain despite being an early adopter and ardent fan of blogdown. I would rather have the .rbind subdomain only than use my own apex and miss out. :)

Thanks a lot for your great work. I really look forward to cotributing to the rbind community.

**Comment by statimatics** [comment]
Thanks a lot. Just like you anticipated, I encountered the same error in #42. I've sent the netlify support a mail to help out.
As regards the domain, I sure find the .rbind.io subdomain very cool and I see rbind exploding with lots of users very soon. It will be such a shame to miss out on my own custom rbind.io subdomain despite being an early adopter and ardent fan of blogdown. I would rather have the .rbind subdomain only than use my own apex and miss out. :)

Thanks a lot for your great work. I really look forward to cotributing to the rbind community soon.

**Comment by yihui** [comment]
You are welcome. I _always_ need help and contributions! 😉 Please feel free to answer any blogdown-related questions here and on StackOverflow before I dive in. That will help me a lot save my time to work on other important things.

**Comment by statimatics** [comment]
So the support team at Netlify helped and my rbind.io domain is live. I also pointed my apex domain to my site by entering an ANAME record with my DNS provider. Finally, the www.* subdomain of my domain is also pointed to my site using a CNAME record.
So everything checks out now I'll close the issue. 
Best regards.
