### ISSUE TITLE
Requesting subdomain for Corey Sparks

### ISSUE THREAD

**Issue by coreysparks** [rbind/support#58]
I have a site on Netlify 
https://promoter-fox-24318.netlify.com/

Could I recieve subdomain on rbind.io?
Thank you!

**Comment by yihui** [comment]
Yes, please specify the subdomain you want.

**Comment by coreysparks** [comment]
sorry,
http://coreysparks.netlify.com/
Thank you!

**Comment by yihui** [comment]
Done.

**Comment by thercast** [comment]
@coreysparks just wanted to let you know that it is also possible to have a domain like `coreysparks.rbind.io`, just let us know if you'd like that instead.

**Comment by road2stat** [comment]
Hi @coreysparks - just a reminder -- please add coreysparks.rbind.io as the custom domain for your Netlify site. Also, please remember to enable the automatic TLS certificates for the custom domain (Domain management -> HTTPS). Thanks!

**Comment by road2stat** [comment]
Hi Professor Sparks @coreysparks - I just want to do another follow up as we are doing some housekeeping for the rbind support tickets which are open for a long time.

Any chance you could kindly add the subdomain to the Netlify website? It probably only takes about two minutes to do so. It would be very helpful though because we will be able to close this ticket.

Thanks!
-Nan

**Comment by road2stat** [comment]
Hi Professor Sparks @coreysparks,

Since we haven't heard back from you on adding the subdomain to an active website for a considerably long time, we have removed the subdomain (`coreysparks.rbind.io`) you requested in this issue. This housekeeping action helps us improve our support quality, reduce security risks, and ensure that the resource is shared equitably by all the community members (#276).

In the future, please feel free to create a new issue to submit subdomain requests when your website is ready. Again, thank you for your support, and we are looking forward to working with you soon.
