### ISSUE TITLE
Domain Request

### ISSUE THREAD

**Issue by Jonghyun-Yun** [rbind/support#587]
## Netlify website address

jyun.netlify.app

## Preferred rbind.io subdomain

jyun.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@Jonghyun-Yun -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by Jonghyun-Yun** [comment]
Hi Nan,

Thanks for the help.
I set up the HTTPS redirection, but the site cannot be reached via https://jyun.rbind.io/
Can you tell me what I missed?

Best,
Jonghyun

**Comment by nanxstats** [comment]
That looks like an SSL issue. A 526 error indicates that Cloudflare (our vendor for the rbind subdomain service) had trouble validating the SSL certificate of the origin server (Netlify).

The only changing variable here seems to be the `*.netlify.app` subdomain for the upstream site ([their announcement](https://community.netlify.com/t/changes-coming-to-netlify-site-urls/8918)). I'm wondering if this has anything to do with it since `.app` domains require mandatory HTTPS connections. That was not the case for `*.github.io` domains or `*.netlify.com` domains we supported before.

I'm cc'ing this to @yihui as he probably has better visibility over the backend than I do.

**Comment by yihui** [comment]
I don't know why it didn't work, but I tried to change the DNS record from jyun.netlify.app to jyun.netlify.com, and jyun.rbind.io seems to work now.

**Comment by Jonghyun-Yun** [comment]
Thanks for the help. 
I see it works now.
