### ISSUE TITLE
Request subdomain

### ISSUE THREAD

**Issue by winsonfzyang** [rbind/support#595]
## Netlify website address

winsonfzyang.netlify.app

## Preferred rbind.io subdomain

winsonfzyang.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@winsonfzyang -we have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be a hint "Check DNS configuration" in the domain section on Netlify after adding the rbind subdomain -- it can be safely ignored.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

(In case it doesn't work due to the `netlify.app` domain, please refer to https://github.com/rbind/support/issues/587 and let us know)

**Comment by winsonfzyang** [comment]
Hello Nan,

I encountered the same error as in #587 . Could you help resolve this?

**Comment by nanxstats** [comment]
Hey @winsonfzyang -thanks for the report, then I guess there's a pattern. I'm tagging @yihui here to update the record to `winsonfzyang.netlify.com` for you as a workaround.

**Comment by yihui** [comment]
Done.

**Comment by winsonfzyang** [comment]
Thanks!! Tested and working!
