### ISSUE TITLE
New site request

### ISSUE THREAD

**Issue by rwerbeck2893** [rbind/support#671]
## Netlify website address

ryanwerbeck.netlify.app

## Preferred rbind.io subdomain

rwerbeck.rbind.io

### Agreement

- [x] By submitting this request, I promise I will at least write one blog post or create one web page on my website after I get the rbind.io subdomain.

**Comment by nanxstats** [comment]
@rwerbeck2893 I see a soft 404 at the current site. Could you please add some content there first?

**Comment by rwerbeck2893** [comment]
Sorry about that, there's some content there I'll be modifying from a template.

**Comment by rwerbeck2893** [comment]
> @rwerbeck2893 -any updates?

I added some content a few days ago that I'm seeing - are you not seeing it? - https://rwerbeck.netlify.app/?
/?

**Comment by nanxstats** [comment]
@rwerbeck2893 In the original request the address was `ryanwerbeck.netlify.app` instead of `rwerbeck.netlify.app` - now I can see it's there.

We have configured the rbind subdomain you requested. Please:

1. Add the rbind subdomain in your Netlify account as the custom domain to your site, as is shown below. Simply use your `subdomain.rbind.io` as the record, no `www` needed.

![](https://user-images.githubusercontent.com/199363/45705707-47b6c580-bb48-11e8-8049-0859c7cc0159.png)

2. There might be messages saying "DNS verification failed" or "check DNS configuration" on Netlify after adding the rbind subdomain -- they can be safely ignored as long as the site renders properly.

3. You may also find the last two sections of [this post](https://yihui.name/en/2017/11/301-redirect/) helpful for redirecting HTTP traffic to HTTPS automatically.

Thanks!
-Nan

**Comment by nanxstats** [comment]
Hey @rwerbeck2893 -just a reminder to add the subdomian on Netlify.

**Comment by nanxstats** [comment]
@rwerbeck2893 Another reminder to add the subdomain.
