### ISSUE TITLE
link behavior

### ISSUE THREAD

**Issue by johnbwilliams** [rbind/support#84]
Hi,

I am getting this criticism of blogdown:

"That blog mechanism doesn't do a good job with links. It tries to open the link in a embedded frame which is not a standard way to do thing. In fact, many bigger sites, such as github do not allow this (note that nothing happens when click on the github links). When click a link, it should completely leave the site and go to the link."     

Is blogdown configurable to open links in a new windows?

Thanks!

**Comment by yihui** [comment]
The criticism does not make sense to me. In particular,

> When click a link, it should completely leave the site and go to the link.

I don't know why this person believed this "should" be the correct behavior or even the "standard". It is quite debatable whether a link should be opened in the current window (tab) or a new window. I don't think there is a correct answer, and personally I don't have an opinion on this. Either way has its pros and cons.

> In fact, many bigger sites, such as github do not allow this.

That is false. Most links you click on Github are opened in the current window, e.g. try https://google.com here. I don't think it should be the "standard", but I believe links on most websites are opened in the current window instead of new windows. The most notable exceptions are those social media tools, such as Twitter. That is because they do not want to lose users, so they prevent users from navigating away from them, which is kind of evil.

If you want to open a link in a new window, you can hold Command and click it if you are on Mac (perhaps Control on other platforms? I'm not sure). Or right click and "Open in new tab".

Of course, you can also configure Hugo's Markdown renderer, Blackfriday, so that it generates `<a target="_blank">` for links, e.g. https://github.com/yihui/twitter-blogdown/blob/b0c2c23d8df570db34bfea657f660d31ff74f3b1/config.toml#L39-L40

In all, I don't think this is proper criticism of blogdown; blogdown is neutral here and does have a special treatment of links. Links are generated by third-party packages such as Blackfriday and Pandoc.
